//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrival
    {
        public long Id_Arrival { get; set; }
        public System.DateTime Date { get; set; }
        public long Id_Purchase { get; set; }
        public long Id_Specialist { get; set; }
        public int Amount { get; set; }
    
        public virtual Purchases Purchases { get; set; }
        public virtual Specialists Specialists { get; set; }
    }
}
